name: multigroupGP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python setup.py install
        pip install flake8 pytest wheel
        pip install -r requirements.txt;
    - name: Test with pytest
      run: |
        pytest tests
